[platformio]
default_envs = garage_node, home_node

[env]
platform = espressif32@6.9.0
board = heltec_wifi_lora_32_V3
framework = arduino
board_build.flash_size = 8MB
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -Wall
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1
lib_deps =
    jgromes/RadioLib@^7.1.2
    bblanchon/ArduinoJson@^7.2.1
    thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.6.1

[env:garage_node]
build_src_filter = +<*> -<home_node.cpp>
build_flags =
    ${env.build_flags}
    -DNODE_GARAGE

[env:home_node]
build_src_filter = +<*> -<garage_node.cpp>
build_flags =
    ${env.build_flags}
    -DNODE_HOME
lib_deps =
    ${env.lib_deps}
    knolleary/PubSubClient@^2.8
